on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
  release:
    types: 
      - published


name: Main Workflow
jobs:
  Build-Core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    
    - name: Get branch name (merge)
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV      

    # - name: Make changes to pull request
    #   run: date +%s > report.txt

    # - name: Create Pull Request
    #   id: cpr
    #   uses: peter-evans/create-pull-request@v6
    #   with:
    #     token: ${{ secrets.TOKEN_PS }}
    #     branch: 'main'
    #     delete-branch: true
    #     title: '[Example]bump for abcd'
    #     body: |
    #       Update report
    #       - Updated with *today's* date
    #       - test
    #       - Auto-generated by [create-pull-request][1]

    #       [1]: https://github.com/peter-evans/create-pull-request
    #     labels: |
    #       report
    #       automated pr
    #     reviewers: michaelhuy
    
