on:
  repository_dispatch:
    types: 
      - update_depends

# repository_dispatch workflows *must* be on the default branch 
#
# expects
# {
#   "event-type": "update_depends",
#   "client_payload": {
#     "env" {
#       "key":".env member",
#       "val": "s3_file"
#      },
#     "commit_msg": "calling repo commit",
#     "branch": "branch to update"
#   }
# }



jobs:
  update:
    runs-on: ubuntu-22.04
    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
        shell: bash

      - uses: actions/checkout@v4

      - name: Make changes to pull request
        run: date +%s > report.txt


      # - name: populate_env
      #   run: |
      #     # clean up the string
      #     original='${{ github.event.client_payload.env.val }}'
      #     fixedpath=$(echo $original|sed -r 's/([\$\.\*\/\[\\^])/\\\1/g')

      #     # rename the keyval inline
      #     sed -i 's/${{ github.event.client_payload.env.key }}=.*/${{ github.event.client_payload.env.key }}='"$fixedpath"'/' .env
      #   shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN_PS }}
          branch: '${{ github.event.client_payload.branch }}'
          delete-branch: true
          title: '[Example]bump for ${{ github.event.client_payload.commit_msg }}'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          reviewers: michaelhuy